name: Github Action for zh_CN LaTeX
description: GitHub Action to compile zh_CN LaTeX documents
author: Cheng XU, HermitSun, FengChendian
inputs:
  root_file:
    description: The root LaTeX file to be compiled
    required: true
  working_directory:
    description: The working directory for the LaTeX engine
  engine:
    description: The LaTeX engine to be invoked
    default: xetex
  args:
    description: Extra arguments to be passed to the LaTeX engine
    default: "-pdf -file-line-error -halt-on-error -interaction=nonstopmode"
  extra_packages:
    description: "[Deprecated] Install extra packages by tlmgr"
  extra_system_packages:
    description: Install extra packages by apk
  pre_compile:
    description: Arbitrary bash codes to be executed before compiling LaTeX documents
  post_compile:
    description: Arbitrary bash codes to be executed after compiling LaTeX documents
  shell_escape:
    description: Instruct xetex to enable --shell-escape
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.root_file }}
    - ${{ inputs.working_directory }}
    - ${{ inputs.engine }}
    - ${{ inputs.args }}
    - ${{ inputs.extra_packages }}
    - ${{ inputs.extra_system_packages }}
    - ${{ inputs.pre_compile }}
    - ${{ inputs.post_compile }}
    - ${{ inputs.shell_escape }}
branding:
  icon: book
  color: blue
