name: Test Github Action
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile basic LaTeX dtx document to cls
        uses: ./
        with:
          root_file: test.dtx
          working_directory: test/
      - name: Check cls files
        run: |
          file test/test.cls | grep -q ' text '
      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: test
          path: test
        if: always()
